name: "2023 PyData Berlin ğŸ‡©ğŸ‡ª generate galery.pdf"
run-name: "ï¸2023 PyData Berlin ğŸ‡©ğŸ‡ª (${{ github.sha }})"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.11.4

defaults:
  run:
    shell: bash -el {0}

jobs:
  lint:
    name: ğŸš¨ Lint Python code
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python environment
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run:
          pip install -r 2023_PyData_Berlin/requirements.txt
      - name: Run Black
        run:
          black 2023_PyData_Berlin --check
      - name: Run Flake8
        run:
          flake8 --config 2023_PyData_Berlin/.flake8 2023_PyData_Berlin

  test:
    name: ğŸ•µ Test Python code
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python environment
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run:
          pip install -r 2023_PyData_Berlin/requirements.txt
      - name: Run tests
        run:
          pytest 2023_PyData_Berlin

  generate-pdf:
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:
      - name: Setup Python environment
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run:
          pip install -r 2023_PyData_Berlin/requirements.txt

      - name: Generate PDF
        run:
          python 2023_PyData_Berlin/src/assemble_plots.py
      - name: Archive PDF
        uses: actions/upload-artifact@v3
        with:
          name: galery.pdf
          path: 2023_PyData_Berlin/results/galery.pdf
