name: "2023 PyData Berlin üá©üá™ generate gallery.pdf"
run-name: "Ô∏è2023 PyData Berlin üá©üá™ (${{ github.sha }})"

on:
  pull_request:
    paths:
      - "2023_PyData_Berlin/**/*.py"
      - "2023_PyData_Berlin/**/*.ipynb"
    branches:
      - main
  push:
    paths:
      - "2023_PyData_Berlin/**/*.py"
      - "2023_PyData_Berlin/**/*.ipynb"
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11

defaults:
  run:
    shell: bash -el {0}

jobs:
  lint:
    name: üö® Lint Python code
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python environment
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 1
      - name: Cache Python dependencies
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('2023_PyData_Berlin/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run:
          pip install -r 2023_PyData_Berlin/requirements.txt
      - name: Run Black
        run:
          black 2023_PyData_Berlin --check
      - name: Run Flake8
        run:
          flake8 --config 2023_PyData_Berlin/.flake8 2023_PyData_Berlin

  test:
    name: üïµ Test Python code
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python environment
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: Cache Python dependencies
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('2023_PyData_Berlin/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run:
          pip install -r 2023_PyData_Berlin/requirements.txt
      - name: Run tests
        run:
          pytest 2023_PyData_Berlin

  generate-pdf:
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:
      - name: Setup Python environment
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: Cache Python dependencies
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('2023_PyData_Berlin/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run:
          pip install -r 2023_PyData_Berlin/requirements.txt

      - name: Generate PDF
        run:
          python 2023_PyData_Berlin/src/assemble_plots.py
      - name: Archive PDF
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: gallery.pdf
          path: 2023_PyData_Berlin/results/gallery.pdf
