name: "2023 PyData Berlin ğŸ‡©ğŸ‡ª generate galery.pdf"
run-name: "ï¸2023 PyData Berlin ğŸ‡©ğŸ‡ª (${{ github.sha }})"
on:
  pull_request:
  push:
    branches: [ main, 2023-pycon-de*]

jobs:
  lint:
    name: ğŸš¨ Lint Python code
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python environment
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.4"
      - name: Install dependencies
        run:
          pip install -r 2023_PyData_Berlin/requirements.txt
      - name: Run Black
        shell: bash -el {0}
        run:
          black 2023_PyConIT --check 2023_PyData_Berlin
      - name: Run Flake8
        shell: bash -el {0}
        run:
          flake8 2023_PyData_Berlin

  test:
    name: ğŸ•µ Test Python code
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python environment
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.4"
      - name: Install dependencies
        run:
          pip install -r 2023_PyData_Berlin/requirements.txt
      - name: Run tests
        shell: bash -el {0}
        run:
          pytest 2023_PyData_Berlin

  generate-pdf:
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:
      - name: Setup Python environment
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.4"
      - name: Install dependencies
        run:
          pip install -r 2023_PyData_Berlin/requirements.txt

      - name: Generate PDF
        shell: bash -el {0}
        run:
          python 2023_PyData_Berlin/src/assemble_plots.py
      - name: Archive PDF
        uses: actions/upload-artifact@v3
        with:
          name: galery.pdf
          path: 2023_PyData_Berlin/results/galery.pdf
